version: '3'

services:
    jenkins:
        #image: jenkins/jenkins:lts
        build: ./jenkins
        container_name: jenkins
        restart: unless-stopped
        volumes:
            - ./data/jenkins/:/var/jenkins_home
        environment:
            - JAVA_OPTS="-Duser.timezone=Asia/Seoul"
        ports:
            - "50000:50000"
            - "5000:8080"
            - "2375:2375"
        networks:
            - webapps_bridge
    gerrit:
        build: ./gerrit
        container_name: gerrit
        restart: unless-stopped
        volumes:
            - ./data/gerrit/etc:/var/gerrit/etc
            - ./data/gerrit/git:/var/gerrit/git
            - ./data/gerrit/index:/var/gerrit/index
            - /data/gerrit/cache:/var/gerrit/cache
            - ./data/gerrit/plugins:/var/gerrit/plugins
        environment:
            - CANONICAL_WEB_URL=http://gerrit2.doosanrobotics.com
        ports:
            - "29418:29418"
        networks:
            - webapps_bridge
    nginx:
        build: ./nginx
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./data/nginx/conf.d:/etc/nginx/conf.d
            - ./data/nginx/log:/var/log/nginx
            - ./data/nginx/docker-entrypoint.d:/docker-entrypoint.d
        ports:
            - "80:80"
            - "443:443"
        networks:
            - webapps_bridge
        depends_on:
            - jenkins
            - gerrit
            - phpldapadmin
            - openldap

networks:
    webapps_bridge:
        driver: bridge
